.github/workflows/main.yml, sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_utils_2d.py, sopht_mpi/utils/mpi_utils_3d.py
=> MPI construct 3d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py, sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_utils_2d.py, sopht_mpi/utils/mpi_utils_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_utils/test_mpi_utils_2d.py, tests/test_utils/test_mpi_utils_3d.py
Fixes #6 with scatter and gather functionalities supporting 3d arrays
=> mpi io communicator 3d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py, sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_utils.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py
=> Storing and accessing kernel_support in kernels

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py
=> mpi advection timestep 2d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/advection_flux_mpi_2d.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py, tests/test_utils/test_mpi_utils_2d.py
=> mpi advection flux and timestep 2d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/outplane_field_curl_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py
=> mpi outplane field curl 2d

tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py, tests/test_utils/test_mpi_utils_2d.py, tests/test_utils/test_mpi_utils_3d.py
=> refactor: test problem size

tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py, tests/test_utils/test_mpi_utils_2d.py, tests/test_utils/test_mpi_utils_3d.py
=> refactor: rename field_io_* -> field_*

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/char_func_from_level_set_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_char_func_from_level_set_mpi_2d.py
=> mpi char func from level set 2d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/update_vorticity_from_velocity_forcing_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_update_vorticity_from_velocity_forcing_mpi_2d.py
=> mpi update vorticity from velocity forcing 2d

tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_char_func_from_level_set_mpi_2d.py
=> fix : zero kernel support index fix for comparison

poetry.lock
Updates index to `sopht-backend`, with new features such as vorticity stretching SSP-RK3 time stepper (Euler forward is observed to be not stable with vorticity stretching term).
=> update: sopht backend with vorticity stretching ssprk3 timestep

sopht_mpi/numeric/eulerian_grid_ops/poisson_solver_2d/UnboundedPoissonSolverMPI2D.py
=> Handle single process run in unbounded poisson solver

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/outplane_field_curl_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py
=> Fix bug in outplane field curl mpi kernel

sopht_mpi/numeric/eulerian_grid_ops/__init__.py, sopht_mpi/sopht_mpi_simulator/__init__.py, sopht_mpi/sopht_mpi_simulator/flow/__init__.py, sopht_mpi/sopht_mpi_simulator/flow/flow_simulators_mpi_2d.py, sopht_mpi/utils/mpi_utils.py
Fixes #45 . I will push the code to demonstrate how this simulator is used in a different PR for the Lamb-Oseen case.
@bhosale2 I need your opinion/suggestion on this. In the unbounded flow simulator class, I have hard-coded the `ghost_size=2` for now. I am not sure how we can get the max(ghost_size) before compiling the kernels, but compiling the kernels requires us to have the ghost communicator defined (and hence ghost size). Maybe we need to have a way to keep track of what kernels will be compiled or something like that. Please let me know what you think, and if you have any suggestions there.
=> MPI-supported 2D unbounded flow simulator

.github/workflows/main.yml
=> removing macos from ci for now

sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_utils_2d.py, tests/test_utils/test_mpi_utils_2d.py
=> MPI communicator for Lagrangian grid fields

sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_utils_2d.py, tests/test_utils/test_mpi_utils_2d.py
Fixes #64 . Merge after #60 is merged
=> Custom master rank for MPIFieldCommunicator

sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_utils_2d.py, tests/test_utils/test_mpi_utils_2d.py
Fixes #63 . Merge after merging #60 and #65 
There will not be any test cases for this. Its functionality will be demonstrated later when we resolve #55
=> MPIPlotter2D support for line and scatter plot

sopht_mpi/numeric/immersed_boundary_ops/VirtualBoundaryForcingMPI.py, sopht_mpi/numeric/immersed_boundary_ops/__init__.py, tests/test_numeric/test_immersed_boundary_ops/test_virtual_boundary_forcing_mpi.py
Fixes #57 . Merge this after merging #58
=> MPI-supported virtual boundary forcing

poetry.lock, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/penalise_field_boundary_mpi_2d.py
=> [WIP] Update pystencil typing to comply with sopht-backend

poetry.lock, pyproject.toml, sopht_mpi/sopht_mpi_simulator/__init__.py, sopht_mpi/sopht_mpi_simulator/immersed_body/__init__.py, sopht_mpi/sopht_mpi_simulator/immersed_body/cosserat_rod/__init__.py, sopht_mpi/sopht_mpi_simulator/immersed_body/cosserat_rod/cosserat_rod_flow_interaction_mpi.py, sopht_mpi/sopht_mpi_simulator/immersed_body/cosserat_rod/cosserat_rod_forcing_grids.py, sopht_mpi/sopht_mpi_simulator/immersed_body/immersed_body_flow_interaction_mpi.py, sopht_mpi/sopht_mpi_simulator/immersed_body/immersed_body_forcing_grid.py, sopht_mpi/sopht_mpi_simulator/immersed_body/rigid_body/__init__.py, sopht_mpi/sopht_mpi_simulator/immersed_body/rigid_body/rigid_body_flow_interaction_mpi.py, sopht_mpi/sopht_mpi_simulator/immersed_body/rigid_body/rigid_body_forcing_grids.py, tests/test_simulator/immersed_body/cosserat_rod/test_cosserat_rod_forcing_grids.py, tests/test_simulator/immersed_body/cosserat_rod/test_mpi_cosserat_rod_flow_interaction.py, tests/test_simulator/immersed_body/rigid_body/test_mpi_rigid_body_flow_interaction.py, tests/test_simulator/immersed_body/rigid_body/test_rigid_body_forcing_grids.py, tests/test_simulator/immersed_body/test_immersed_body_forcing_grid.py, tests/test_simulator/immersed_body/test_immersed_body_interaction_mpi.py
Fixes #59 , #72 , #74 
The interactor will coordinate and generate the desired `forcing_grid_cls` only on the master rank, other ranks will initialize an `EmptyForcingGrid`. This empty grid will have the abstract methods of a forcing grid class initialized as a no-op (i.e. pass). This way, only the master rank contains useful information on the forcing grid, which then external simulator such as elastica will communicate with only that master rank (since it contains the **global** quantities for the immersed body such as position, velocity, forcing field).
Given the overall structure above, notice that I have named the interactor with post-fix `MPI` and not for the forcing grids, since the forcing grid essentially need not perform any MPI communication. In other words, the forcing grids …
=> Immersed flow interaction and forcing grid

examples/2d_examples/FlowPastCylinderCase/flow_past_cylinder.py, sopht_mpi/utils/mpi_utils_2d.py
Fixes #55 . Merge after merging #73 
Please find qualitative and quantitative comparisons between `sopht-mpi` and `sopht-examples` below for `grid_size_x=512`, `grid_size_y=grid_size_x // 2` and `precision="double"`.
-------------------------------------
https://user-images.githubusercontent.com/12764958/201457542-2a86252e-ced6-4675-b66a-94ae571bb5b6.mp4
-------------------------------------
https://user-images.githubusercontent.com/12764958/201457408-17c61c4a-e780-44cd-8e7d-9ece522a769c.mp4
-------------------------------------
=> Flow past cylinder

examples/2d_examples/FlowPastCylinderCase/flow_past_cylinder.py, examples/2d_examples/FlowPastRodCase/flow_past_rod.py, sopht_mpi/sopht_mpi_simulator/__init__.py, sopht_mpi/sopht_mpi_simulator/flow/flow_simulators_mpi_2d.py, sopht_mpi/sopht_mpi_simulator/utils/__init__.py, sopht_mpi/sopht_mpi_simulator/utils/grid_utils.py
Fixes #82 
I also reran the currently available example cases and they reproduced the same results as before.
=> Refactor position as vector field

examples/2d_examples/FlowPastCylinderCase/flow_past_cylinder.py, examples/2d_examples/FlowPastRodCase/flow_past_rod.py, poetry.lock, pyproject.toml
Fixes #84 . Merge after merging #83 
@bhosale2 I have also implemented some refactoring in the flow past cylinder case to take input arguments as well. Would be glad to port these changes over to `sopht-examples` if you want.
=> cli arguments for example cases

examples/2d_examples/LambOseenVortexCase/lamb_oseen_vortex.py
Minor refactoring. Overlooking in the last iteration.
=> refactor: lamb oseen vortex example

examples/2d_examples/FlowPastCylinderCase/flow_past_cylinder.py, examples/2d_examples/FlowPastRodCase/flow_past_rod.py, examples/2d_examples/LambOseenVortexCase/lamb_oseen_vortex.py, sopht_mpi/sopht_mpi_simulator/flow/flow_simulators_mpi_2d.py, sopht_mpi/sopht_mpi_simulator/immersed_body/immersed_body_flow_interaction_mpi.py, sopht_mpi/sopht_mpi_simulator/immersed_body/immersed_body_forcing_grid.py, sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_logger.py, sopht_mpi/utils/mpi_utils_2d.py, sopht_mpi/utils/mpi_utils_3d.py, tests/test_simulator/immersed_body/test_immersed_body_forcing_grid.py, tests/test_simulator/immersed_body/test_immersed_body_interaction_mpi.py, tests/test_utils/test_mpi_logger.py, tests/test_utils/test_mpi_utils_2d.py
Fixes #31 
This PR contains a minimal implementation of a logger that works similarly to a single-process environment, as well as the refactoring to replace print statements with log messages.
For convenience and as an illustration, the terminal outputs for the flow past cylinder example case are as below.
```
$ mpirun -np 4 python flow_past_cylinder.py
Grid size: (256, 512)
Reynolds number: 200.0
===============================================
2D flow domain initialized with:
X axis from 0.0 to 1.0
Y axis from 0.0 to 0.5
Please initialize bodies within these bounds!
===============================================
==========================================================
2D body forcing grid generated, this assumes the body
moves in XY plane! Please initialize your body such that
ensuing …
```
=> MPI-supported logger

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py
=> fix : bug with setting diffusion flux physical domain boundary

sopht_mpi/numeric/eulerian_grid_ops/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/diffusion_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_flux_mpi_3d.py
=> feat: 3d diffusion kernel for scalar and vector field

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/diffusion_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_timestep_mpi_3d.py
=> feat: diffusion timestep kernel 3d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/advection_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_flux_mpi_3d.py
Fixes #103 , with some minor changes in `test_advection_flux_mpi_2d.py` to make grid dimension more explicit.
=> Advection flux kernel 3d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/advection_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_timestep_mpi_3d.py
Fixes #104 , merge after #105 .
=> Advection timestep kernel 2d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/brinkmann_penalise_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_brinkmann_penalise_mpi_3d.py
=> Brinkmann penalise kernel 3d

tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_unbounded_poisson_solver_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_char_func_from_level_set_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_penalise_field_boundary_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_update_vorticity_from_velocity_forcing_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_brinkmann_penalise_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_char_func_from_level_set_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_divergence_mpi_3d.py, tests/test_numeric/test_immersed_boundary_ops/test_virtual_boundary_forcing_mpi.py, tests/test_simulator/immersed_body/cosserat_rod/test_mpi_cosserat_rod_flow_interaction.py, tests/test_simulator/immersed_body/rigid_body/test_mpi_rigid_body_flow_interaction.py, tests/test_utils/test_mpi_utils_2d.py, tests/test_utils/test_mpi_utils_3d.py
=> Refactor test suite

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/curl_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_curl_mpi_3d.py
Fixes #113 . I merged #121 here so maybe merge that to `main` first before reviewing this. Thanks!
=> Curl kernel 3d

sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/penalise_field_boundary_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_penalise_field_boundary_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_penalise_field_boundary_mpi_3d.py
Fixes #123 . Same thing here, I merged #121  here so maybe merge that to `main` first before reviewing this. Thanks!
=> Penalise field boundary kernel 3d

tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_char_func_from_level_set_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_update_vorticity_from_velocity_forcing_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_brinkmann_penalise_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_char_func_from_level_set_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_curl_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_divergence_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_penalise_field_boundary_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_update_vorticity_from_velocity_forcing_mpi_3d.py
Fixes #125 . Minor refactoring.
=> Remove unnecessary bcast in tests

sopht_mpi/numeric/eulerian_grid_ops/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/poisson_solver_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/poisson_solver_3d/fft_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_3d/test_fft_mpi_3d.py
=> FFT kernel 3d

examples/2d_examples/FlowPastCylinderCase/flow_past_cylinder.py, examples/2d_examples/FlowPastRodCase/flow_past_rod.py, examples/2d_examples/LambOseenVortexCase/lamb_oseen_vortex.py, sopht_mpi/simulator/flow/flow_simulators_mpi_2d.py
=> Internalize time stepper in 2d simulator

tests/test_simulator/test_flow/test_flow_simulators_2d.py
=> 2d flow simulator test

sopht_mpi/utils/mpi_utils_2d.py, sopht_mpi/utils/mpi_utils_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_unbounded_poisson_solver_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_3d/test_fft_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_char_func_from_level_set_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_penalise_field_boundary_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_update_vorticity_from_velocity_forcing_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_advection_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_brinkmann_penalise_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_char_func_from_level_set_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_curl_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_flux_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_diffusion_timestep_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_divergence_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_penalise_field_boundary_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_update_vorticity_from_velocity_forcing_mpi_3d.py, tests/test_numeric/test_immersed_boundary_ops/test_virtual_boundary_forcing_mpi_2d.py, tests/test_utils/test_mpi_utils_2d.py, tests/test_utils/test_mpi_utils_3d.py
Fixes #142 
Similarly here I have made the scatter and gather function name explicit for scalar and vector fields.
=> Refactor field comm for scalar and vector fields

tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_update_vorticity_from_velocity_forcing_mpi_2d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_curl_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_update_vorticity_from_velocity_forcing_mpi_3d.py
Refactoring some indexing bugs in test cases.
=> Fix minor indexing bug in tests cases

.gitignore, examples/2d_examples/FlowPastRodCase/flow_past_rod.py, sopht_mpi/utils/__init__.py, sopht_mpi/utils/mpi_io.py, sopht_mpi/utils/mpi_utils_2d.py, tests/test_utils/test_mpi_io_2d.py, tests/test_utils/test_mpi_io_3d.py
Fixes #37 
I also included a use case for the flow past rod example. Please find the Paraview rendering for the example case below.
https://user-images.githubusercontent.com/12764958/208522758-2b85f813-709d-4bde-a512-9ba1ef6c215a.mp4
=> MPI-supported IO

pyproject.toml, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/__init__.py, sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_3d/laplacian_filter_mpi_3d.py, tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_3d/test_laplacian_filter_mpi_3d.py
=> Laplacian filter kernel 3d

sopht_mpi/simulator/flow/__init__.py, sopht_mpi/simulator/flow/flow_simulators_mpi_2d.py, sopht_mpi/simulator/flow/flow_simulators_mpi_3d.py, tests/test_simulator/test_flow/test_flow_simulators_3d.py
=> MPI-supported 3D unbounded flow simulator

sopht_mpi/simulator/flow/flow_simulators_mpi_3d.py, tests/test_simulator/test_flow/test_flow_simulators_2d.py, tests/test_simulator/test_flow/test_flow_simulators_3d.py
Adding a few more test cases for flow simulators, and fixed a minor bug in get vorticity divergence function in 3d flow simulator.
=> Additional flow simulator tests

doc/clusters/README.md, doc/clusters/submit_expanse.sh, doc/clusters/submit_stampede2.sh
Fixes #173 , also removed unnecessary export directives in the sample submission script, since some facility does not encourage it while others are optional.
=> Additional documentation on setting pystencils cache dir

doc/clusters/README.md, doc/clusters/submit_bridges2.sh
Fixes #184 
Note: The CI will fail as expected due to #182 . I will push a temporary fix soon when resolving #183
=> 184 bridges
